### ISSUE TITLE
Sujerinha no código-fonte main.cu

### ISSUE THREAD

**Issue by t1keshi** [hpc-fci-mackenzie/cfrk#8]
Da linha 282 a 287 tem uma "sujerinha" que o git coloca quando faz o merge. Esse problema ocorre em todas as branches.

**Comment by calebepb** [comment]
Sabe qual é a branch? Se importaria o link para o arquivo aqui?

**Comment by t1keshi** [comment]
É aquele problema que comentei no Slack. Estou corrigindo agora e já faço o merge request.

https://github.com/hpc-fci-mackenzie/cfrk/blob/5cd38049731eea86fd036872036729831e6cfa42/src/main.cu#L282-L287
